name: Executar Testes Cypress

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress
        run: npx cypress run

      - name: Upload de vídeos e resultados (Artifacts)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/videos/
